// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0NynLjm6T_4kmkhZb4wbWojRu8L3FP04',
    appId: '1:1079751763377:web:3526d358563f7c8c888990',
    messagingSenderId: '1079751763377',
    projectId: 'hostelapp1-23342',
    authDomain: 'hostelapp1-23342.firebaseapp.com',
    storageBucket: 'hostelapp1-23342.appspot.com',
    measurementId: 'G-FNGMWY2B3R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQv_ZaSpAHAotsXMgITTJNlryuRTEX1pY',
    appId: '1:1079751763377:android:c2fda6237026b1b7888990',
    messagingSenderId: '1079751763377',
    projectId: 'hostelapp1-23342',
    storageBucket: 'hostelapp1-23342.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKjhhP2dHTxRFvWwIs5SkmeyTQAnmZs40',
    appId: '1:1079751763377:ios:21640c4b22e225e4888990',
    messagingSenderId: '1079751763377',
    projectId: 'hostelapp1-23342',
    storageBucket: 'hostelapp1-23342.appspot.com',
    iosBundleId: 'com.example.hostelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKjhhP2dHTxRFvWwIs5SkmeyTQAnmZs40',
    appId: '1:1079751763377:ios:b1088944d2c11dda888990',
    messagingSenderId: '1079751763377',
    projectId: 'hostelapp1-23342',
    storageBucket: 'hostelapp1-23342.appspot.com',
    iosBundleId: 'com.example.hostelApp.RunnerTests',
  );
}
